// /data.js
export const fakeApiData = {
    courts: [
      { id: 1, name: "Futsal Court" },
      { id: 2, name: "Multipurpose Court" },
      { id: 3, name: "Pickle Ball/Badminton Court" },
    ],
    dates: [
      { id: 1, date: "1", day: "Wednesday", month: "Nov" },
      { id: 2, date: "2", day: "Thursday", month: "Nov" },
      { id: 3, date: "3", day: "Friday", month: "Nov" },
      { id: 4, date: "4", day: "Saturday", month: "Nov" },
      { id: 5, date: "5", day: "Sunday", month: "Nov" },
      { id: 6, date: "6", day: "Monday", month: "Nov" },
      { id: 7, date: "7", day: "Tuesday", month: "Nov" },
      { id: 8, date: "8", day: "Wednesday", month: "Nov" },
      { id: 9, date: "9", day: "Thursday", month: "Nov" },
      { id: 10, date: "10", day: "Friday", month: "Nov" },
      { id: 11, date: "11", day: "Saturday", month: "Nov" },
      { id: 12, date: "12", day: "Sunday", month: "Nov" },
      { id: 13, date: "13", day: "Monday", month: "Nov" },
      { id: 14, date: "14", day: "Tuesday", month: "Nov" },
      { id: 15, date: "15", day: "Wednesday", month: "Nov" },
      { id: 16, date: "16", day: "Thursday", month: "Nov" },
      { id: 17, date: "17", day: "Friday", month: "Nov" },
      { id: 18, date: "18", day: "Saturday", month: "Nov" },
      { id: 19, date: "19", day: "Sunday", month: "Nov" },
      { id: 20, date: "20", day: "Monday", month: "Nov" },
      { id: 21, date: "21", day: "Tuesday", month: "Nov" },
      { id: 22, date: "22", day: "Wednesday", month: "Nov" },
      { id: 23, date: "23", day: "Thursday", month: "Nov" },
      { id: 24, date: "24", day: "Friday", month: "Nov" },
      { id: 25, date: "25", day: "Saturday", month: "Nov" },
      { id: 26, date: "26", day: "Sunday", month: "Nov" },
      { id: 27, date: "27", day: "Monday", month: "Nov" },
      { id: 28, date: "28", day: "Tuesday", month: "Nov" },
      { id: 29, date: "29", day: "Wednesday", month: "Nov" },
      { id: 30, date: "30", day: "Thursday", month: "Nov" },
      { id: 31, date: "1", day: "Friday", month: "Dec" },
      { id: 32, date: "2", day: "Saturday", month: "Dec" },
      { id: 33, date: "3", day: "Sunday", month: "Dec" },
      { id: 34, date: "4", day: "Monday", month: "Dec" },
      { id: 35, date: "5", day: "Tuesday", month: "Dec" },
      { id: 36, date: "6", day: "Wednesday", month: "Dec" },
      { id: 37, date: "7", day: "Thursday", month: "Dec" },
      { id: 38, date: "8", day: "Friday", month: "Dec" },
      { id: 39, date: "9", day: "Saturday", month: "Dec" },
      { id: 40, date: "10", day: "Sunday", month: "Dec" },
      { id: 41, date: "11", day: "Monday", month: "Dec" },
      { id: 42, date: "12", day: "Tuesday", month: "Dec" },
      { id: 43, date: "13", day: "Wednesday", month: "Dec" },
      { id: 44, date: "14", day: "Thursday", month: "Dec" },
      { id: 45, date: "15", day: "Friday", month: "Dec" },
      { id: 46, date: "16", day: "Saturday", month: "Dec" },
      { id: 47, date: "17", day: "Sunday", month: "Dec" },
      { id: 48, date: "18", day: "Monday", month: "Dec" },
      { id: 49, date: "19", day: "Tuesday", month: "Dec" },
      { id: 50, date: "20", day: "Wednesday", month: "Dec" },
      { id: 51, date: "21", day: "Thursday", month: "Dec" },
      { id: 52, date: "22", day: "Friday", month: "Dec" },
      { id: 53, date: "23", day: "Saturday", month: "Dec" },
      { id: 54, date: "24", day: "Sunday", month: "Dec" },
      { id: 55, date: "25", day: "Monday", month: "Dec" },
      { id: 56, date: "26", day: "Tuesday", month: "Dec" },
      { id: 57, date: "27", day: "Wednesday", month: "Dec" },
      { id: 58, date: "28", day: "Thursday", month: "Dec" },
      { id: 59, date: "29", day: "Friday", month: "Dec" },
      { id: 60, date: "30", day: "Saturday", month: "Dec" },
      { id: 61, date: "31", day: "Sunday", month: "Dec" },
    ],
    slots: [
      { time: "01:00PM", available: false },
      { time: "01:30PM", available: true },
      { time: "02:00PM", available: true },
      { time: "02:30PM", available: false },
      { time: "03:00PM", available: true },
      { time: "03:30PM", available: true },
      { time: "04:00PM", available: false },
      { time: "04:30PM", available: true },
      { time: "05:00PM", available: true },
      { time: "05:30PM", available: false },
      { time: "06:00PM", available: true },
      { time: "06:30PM", available: true },
      { time: "07:00PM", available: false },
      { time: "07:30PM", available: true },
      { time: "08:00PM", available: true },
      { time: "08:30PM", available: true },
      { time: "09:00PM", available: true },
      { time: "09:30PM", available: true },
      { time: "10:00PM", available: true },
      { time: "10:30PM", available: true },
    ],
    slotPrice: 5000,
  };