// /data.js
export const fakeApiData = {
  courts: [
    { id: 1, name: "Futsal Court" },
    { id: 2, name: "Multipurpose Court" },
    { id: 3, name: "Pickle Ball/Badminton Court" },
  ],
  dates: [
    { id: 1, date: "1", day: "Wednesday", month: "Nov", year: "2023" },
    { id: 2, date: "2", day: "Thursday", month: "Nov", year: "2023" },
    { id: 3, date: "3", day: "Friday", month: "Nov", year: "2023" },
    { id: 4, date: "4", day: "Saturday", month: "Nov", year: "2023" },
    { id: 5, date: "5", day: "Sunday", month: "Nov", year: "2023" },
    { id: 6, date: "6", day: "Monday", month: "Nov", year: "2023" },
    { id: 7, date: "7", day: "Tuesday", month: "Nov", year: "2023" },
    { id: 8, date: "8", day: "Wednesday", month: "Nov", year: "2023" },
    { id: 9, date: "9", day: "Thursday", month: "Nov", year: "2023" },
    { id: 10, date: "10", day: "Friday", month: "Nov", year: "2023" },
    { id: 11, date: "11", day: "Saturday", month: "Nov", year: "2023" },
    { id: 12, date: "12", day: "Sunday", month: "Nov", year: "2023" },
    { id: 13, date: "13", day: "Monday", month: "Nov", year: "2023" },
    { id: 14, date: "14", day: "Tuesday", month: "Nov", year: "2023" },
    { id: 15, date: "15", day: "Wednesday", month: "Nov", year: "2023" },
    { id: 16, date: "16", day: "Thursday", month: "Nov", year: "2023" },
    { id: 17, date: "17", day: "Friday", month: "Nov", year: "2023" },
    { id: 18, date: "18", day: "Saturday", month: "Nov", year: "2023" },
    { id: 19, date: "19", day: "Sunday", month: "Nov", year: "2023" },
  ],
  slots: [
    { time: "01:00PM", available: false },
    { time: "01:30PM", available: true },
    { time: "02:00PM", available: true },
    { time: "02:30PM", available: false },
    { time: "03:00PM", available: true },
    { time: "03:30PM", available: true },
    { time: "04:00PM", available: false },
    { time: "04:30PM", available: true },
    { time: "05:00PM", available: true },
    { time: "05:30PM", available: false },
    { time: "06:00PM", available: true },
    { time: "06:30PM", available: true },
    { time: "07:00PM", available: false },
    { time: "07:30PM", available: true },
    { time: "08:00PM", available: true },
    { time: "08:30PM", available: true },
    { time: "09:00PM", available: true },
    { time: "09:30PM", available: true },
    { time: "10:00PM", available: true },
    { time: "10:30PM", available: true },
  ],
  slotPrice: 5000,
};